name: cached_image
description: Convenient wrapper over flutter_cached_network_image with some additional features
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  collection:

  flutter_cache_manager: ^3.3.1
  cached_network_image: ^3.3.1

flutter:
  assets:
    - assets/1x1.png

dev_dependencies:
  flutter_lints:
  test: